# SPDX-FileCopyrightText: © 2026 synack.d
#
# SPDX-License-Identifier: BSD-3-Clause

name: reuse

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  reuse:
    name: reuse
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: REUSE Compliance Check
        run: pipx run --backend pip --spec reuse==6.2.0 reuse lint --lines
